version: '3.9'
services:
  user:
    build: .
    container_name: core_profile
    restart: always
    hostname: profile
    ports:
     - "4002:4002"
    networks:
      - backend
    links:
      - shard1svr1
      - shard1svr2
      - shard1svr3
networks:
  backend:
    name: microserver_backend
    driver: bridge
